language: go

sudo: false

go:
    - "1.13"
    - "1.14"

install:
    - go get -t ./...
    - go install ./...
    - go get -u github.com/kisielk/errcheck

script:
    - CGO_ENABLED=0 go build -v .
    - go test -v ./...
    - errcheck ./...
